name: Deploy Python project to Azure Function App

on:
  push:
    branches:
      - main  # Trigger deployment on main branch push

env:
  AZURE_FUNCTIONAPP_NAME: 'rk54'   # Set your Azure Function App name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'       # Set the path to your function app project, defaults to the repository root
  PYTHON_VERSION: '3.9'                     # Set the Python version to use (e.g., '3.6', '3.7', '3.8')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true

